######################################################################
# Automatically generated by qmake (1.07a) Thu Sep 23 14:38:50 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += game.h graphics.h logger.h utils.h MainWindow.h
FORMS += MainWindow.ui
SOURCES += game.cpp graphics.cpp logger.cpp main.cpp utils.cpp MainWindow.cpp
